<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('order_items')->insert([
            [
                'name' => 'Mango Lassi',
                'slug' => 'mango-lassi',
                'code' => '700',
                'bag_points' => '0',
                'description_en' => 'Pureed Indian mangoes, yoghurt & water',
                'description_dk' => 'Blendede indiske mangoer, yoghurt og vand',
                'portion' => '33 cl',
                'section' => 'bn-drinks',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 30,
            ],
            [
                'name' => 'Mint, Ginger & Lime Lemonade',
                'slug' => 'mint-ginger-and-lime-lemonade',
                'code' => '710',
                'bag_points' => '0',
                'description_en' => 'Lemonade with mint, ginger & lime',
                'description_dk' => 'Lemonade med mynte, ingefær & lime',
                'portion' => '33 cl',
                'section' => 'bn-drinks',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 30,
            ],
            [
                'name' => 'Kingfisher (Beer)',
                'slug' => 'kingfisher-beer',
                'code' => '740',
                'bag_points' => '0',
                'description_en' => 'India’s most celebrated beer. Classic Asian lager beer',
                'description_dk' => 'Indiens mest velkendte øl. Klassisk asiatisk lager-øl',
                'portion' => '33 cl',
                'section' => 'bn-drinks',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 40,
            ],
            [
                'name' => 'Coca-Cola',
                'slug' => 'coca-cola',
                'code' => '750',
                'bag_points' => '0',
                'description_en' => 'Coca-Cola',
                'description_dk' => 'Coca-Cola',
                'portion' => '50 cl',
                'section' => 'bn-drinks',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 30,
            ],
            [
                'name' => 'Coca-Cola Zero',
                'slug' => 'coca-cola-zero',
                'code' => '751',
                'bag_points' => '0',
                'description_en' => 'Coca-Cola Zero',
                'description_dk' => 'Coca-Cola Zero',
                'portion' => '50 cl',
                'section' => 'bn-drinks',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 30,
            ],
//            [
//                'name' => 'NODA Ginger Lemongrass',
//                'slug' => 'noda-ginger-lemongrass',
//                'code'=>'760',
//                'bag_points'=>'0',
//                'description_en' => 'Organic fizzy drink',
//                'description_dk' => 'Økologisk kulsyreholdig drik med ingefær og citrongræs',
//                'portion' => '25 cl',
//                'section' => 'bn-drinks',
//                'veg' => false,
//                'vegan' => false,
//                'nuts' => false,
//                'dairy' => false,
//                'gluten' => false,
//                'chili' => false,
//                'price' => 30,
//            ],
//            [
//                'name' => 'NODA Sicilian Lemon',
//                'slug' => 'noda-sicilian-lemon',
//                'code'=>'761',
//                'bag_points'=>'0',
//                'description_en' => 'Organic fizzy drink',
//                'description_dk' => 'Økologisk kulsyreholdig drik med ingefær og citrongræs',
//                'portion' => '25 cl',
//                'section' => 'bn-drinks',
//                'veg' => false,
//                'vegan' => false,
//                'nuts' => false,
//                'dairy' => false,
//                'gluten' => false,
//                'chili' => false,
//                'price' => 30,
//            ],
//            [
//                'name' => 'NODA Pink Grapefruit',
//                'slug' => 'noda-pink-grapefruit',
//                'code'=>'762',
//                'bag_points'=>'0',
//                'description_en' => 'Organic fizzy drink',
//                'description_dk' => 'Økologisk kulsyreholdig drik med ingefær og citrongræs',
//                'portion' => '25 cl',
//                'section' => 'bn-drinks',
//                'veg' => false,
//                'vegan' => false,
//                'nuts' => false,
//                'dairy' => false,
//                'gluten' => false,
//                'chili' => false,
//                'price' => 30,
//            ],
            [
                'name' => 'Spring Water',
                'slug' => 'spring-water',
                'code' => '770',
                'bag_points' => '0',
                'description_en' => 'Spring water',
                'description_dk' => 'Kildevand',
                'portion' => '50 cl',
                'section' => 'bn-drinks',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 30,
            ],
            [
                'name' => 'Sparkling Water',
                'slug' => 'sparkling-water',
                'code' => '771',
                'bag_points' => '0',
                'description_en' => 'Sparkling water',
                'description_dk' => 'Danskvand',
                'portion' => '50 cl',
                'section' => 'bn-drinks',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 30,
            ],
            [
                'name' => 'Red Wine',
                'slug' => 'red-wine',
                'code' => '780',
                'bag_points' => '0',
                'description_en' => 'Red Wine',
                'description_dk' => 'Rødvin',
                'portion' => '37.5 cl',
                'section' => 'bn-drinks',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 80,
            ],
            [
                'name' => 'White Wine',
                'slug' => 'white-wine',
                'code' => '781',
                'bag_points' => '0',
                'description_en' => 'White Wine',
                'description_dk' => 'Hvidvin',
                'portion' => '37.5 cl',
                'section' => 'bn-drinks',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 80,
            ],
            [
                'name' => 'Tandoori Chicken',
                'slug' => 'tandoori-chicken',
                'code' => '200',
                'bag_points' => '2',
                'description_en' => 'Chicken drumstick & thigh marinated in tandoori spices and baked in a tandoor oven',
                'description_dk' => 'Kyllingelår marineret i tandoorikrydderier & bagt i tandoor ovn',
                'portion' => 'approx. 300 g',
                'section' => 'bn-single-meals',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 60,
            ],
            [
                'name' => 'Chicken Biryani',
                'slug' => 'chicken-biryani',
                'code' => '211',
                'bag_points' => '2',
                'description_en' => 'Seasoned rice dish with an Oriental nut mix & raisins. With tandoori chicken fillet marinated with spices',
                'description_dk' => 'Krydret risret med orientalsk nøddemix & rosiner. Med tandoori kyllingefilet marineret i krydderier',
                'portion' => 'approx. 500 g',
                'section' => 'bn-single-meals',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Lamb Biryani',
                'slug' => 'lamb-biryani',
                'code' => '212',
                'bag_points' => '2',
                'description_en' => 'Seasoned rice dish with an Oriental nut mix & raisins. With tender chunks of prime New Zealand lamb',
                'description_dk' => 'Krydret risret med orientalsk nøddemix & rosiner. Med møre stykker af det bedste lammekød fra New Zealand',
                'portion' => 'approx. 500 g',
                'section' => 'bn-single-meals',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 120,
            ],
            [
                'name' => 'Lamb Kebab Biryani',
                'slug' => 'lamb-kebab-biryani',
                'code' => '213',
                'bag_points' => '2',
                'description_en' => 'Seasoned rice dish with an Oriental nut mix & raisins with in house minced lamb kebabs (grilled).',
                'description_dk' => 'Krydret risret med orientalsk nøddemix & rosiner. Med hjemmelavede kebab af hakket og grillet lammekød',
                'portion' => 'approx. 500 g',
                'section' => 'bn-single-meals',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Paneer Biryani',
                'slug' => 'paneer-biryani',
                'code' => '214',
                'bag_points' => '2',
                'description_en' => 'Seasoned rice dish with an Oriental nut mix & raisins. With un-aged, non-melting farmer cheese',
                'description_dk' => 'Krydret risret med orientalsk nøddemix & rosiner. Med traditionel indisk ulagret, fast ost',
                'portion' => 'approx. 500 g',
                'section' => 'bn-single-meals',
                'veg' => true,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Chicken Platter',
                'slug' => 'chicken-platter',
                'code' => '221',
                'bag_points' => '2',
                'description_en' => 'A curry of our Chef\'s choice, served with basmati rice. With tandoori chicken fillet marinated with spices',
                'description_dk' => 'Kokkens udvalgte curry, serveret med basmati-ris. Med tandoori kyllingefilet marineret i krydderier',
                'portion' => 'approx. 500 g',
                'section' => 'bn-single-meals',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Lamb Platter',
                'slug' => 'lamb-platter',
                'code' => '222',
                'bag_points' => '2',
                'description_en' => 'A curry of our Chef\'s choice, served with basmati rice. With tender chunks of prime New Zealand lamb',
                'description_dk' => 'Kokkens udvalgte curry, serveret med basmati-ris. Med møre stykker af det bedste lammekød fra New Zealand',
                'portion' => 'approx. 500 g',
                'section' => 'bn-single-meals',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 120,
            ],
            [
                'name' => 'Lamb Kebab Platter',
                'slug' => 'lamb-kebab-platter',
                'code' => '223',
                'bag_points' => '2',
                'description_en' => 'A curry of our Chef\'s choice, served with basmati rice with in house minced lamb kebabs (grilled).',
                'description_dk' => 'Kokkens udvalgte curry, serveret med basmati-ris. Med hjemmelavede kebab af hakket og grillet lammekød',
                'portion' => 'approx. 500 g',
                'section' => 'bn-single-meals',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Paneer Platter',
                'slug' => 'paneer-platter',
                'code' => '224',
                'bag_points' => '2',
                'description_en' => 'A curry of our Chef\'s choice, served with basmati rice. With un-aged, non-melting farmer cheese',
                'description_dk' => 'Kokkens udvalgte curry, serveret med basmati-ris. Med traditionel indisk ulagret, fast ost',
                'portion' => 'approx. 500 g',
                'section' => 'bn-single-meals',
                'veg' => true,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Dal',
                'slug' => 'dal',
                'code' => '300',
                'bag_points' => '2',
                'description_en' => 'Seasonal lentils prepared with fried garlic',
                'description_dk' => 'Årstidens linser tilberedt med stegt hvidløg',
                'portion' => 'approx. 400 g',
                'section' => 'bn-veg',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 95,
            ],
            [
                'name' => 'Mushrooms Fenugreek',
                'slug' => 'mushrooms-fenugreek',
                'code' => '310',
                'bag_points' => '2',
                'description_en' => 'Seasonal mushrooms with fenugreek, garlic & fresh coriander',
                'description_dk' => 'Årstidens svampe med bukkehorn, hvidløg & frisk koriander',
                'portion' => 'approx. 400 g',
                'section' => 'bn-veg',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 95,
            ],
            [
                'name' => 'Spinach Bhaji',
                'slug' => 'spinach-bhaji',
                'code' => '320',
                'bag_points' => '2',
                'description_en' => 'Whole-leafed spinach with fenugreek, fresh tomatoes & garlic',
                'description_dk' => 'Hele spinatblade med bukkehorn, tomatstykker & hvidløg',
                'portion' => 'approx. 400 g',
                'section' => 'bn-veg',
                'veg' => true,
                'vegan' => false,
                'nuts' => false,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 95,
            ],
            [
                'name' => 'Aloo Gobi',
                'slug' => 'aloo-gobi',
                'code' => '330',
                'bag_points' => '2',
                'description_en' => 'Spicy pan-fried potatoes with cauliflower',
                'description_dk' => 'Krydrede pandestegte kartofler med blomkål',
                'portion' => 'approx. 400 g',
                'section' => 'bn-veg',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => true,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 95,
            ],
            [
                'name' => 'Aloo Methi',
                'slug' => 'aloo-methi',
                'code' => '340',
                'bag_points' => '2',
                'description_en' => 'Pan-fried potatoes with fenugreek, tomatoes, ginger & garlic',
                'description_dk' => 'Pandestegte kartofler med bukkehorn, tomater, ingefær & hvidløg',
                'portion' => 'approx. 400 g',
                'section' => 'bn-veg',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 95,
            ],
            [
                'name' => 'Mattar Paneer',
                'slug' => 'mattar-paneer',
                'code' => '350',
                'bag_points' => '2',
                'description_en' => 'Sweet green peas & stir-fried paneer in a curry with ginger, garlic, turmeric & fenugreek',
                'description_dk' => 'Søde grønne ærter & stegt paneer i en curry med ingefær, hvidløg, gurkemeje & bukkehorn',
                'portion' => 'approx. 400 g',
                'section' => 'bn-veg',
                'veg' => true,
                'vegan' => false,
                'nuts' => false,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Bangan Burtha',
                'slug' => 'bangan-burtha',
                'code' => '370',
                'bag_points' => '2',
                'description_en' => 'Oven baked aubergines with onion, ginger & garlic',
                'description_dk' => 'Ovnbagte auberginer med løg, ingefær og hvidløg',
                'portion' => 'approx. 400 g',
                'section' => 'bn-veg',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 95,
            ],
            [
                'name' => 'Mixed Veg',
                'slug' => 'mixed-veg',
                'code' => '380',
                'bag_points' => '2',
                'description_en' => 'Stir-fried seasonal vegetables in a spicy curry',
                'description_dk' => 'Sæsonens stegte grøntsager i en krydret curry',
                'portion' => 'approx. 400 g',
                'section' => 'bn-veg',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => true,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 95,
            ],
            [
                'name' => 'Channa Masala',
                'slug' => 'channa-masala',
                'code' => '390',
                'bag_points' => '2',
                'description_en' => 'Protein-rich chickpeas with black pepper & nigella seeds',
                'description_dk' => 'Proteinrige indiske kikærter med sort peber & nigellafrø',
                'portion' => 'approx. 400 g',
                'section' => 'bn-veg',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 95,
            ],
            [
                'name' => 'Butter Chicken',
                'slug' => 'butter-chicken',
                'code' => '501',
                'bag_points' => '2',
                'description_en' => 'Tangy tomato curry with an Oriental nut mix. With tandoori chicken fillet marinated with spices',
                'description_dk' => 'Syrlig tomatcurry med orientalsk nøddemix. Med tandoori kyllingefilet marineret i krydderier',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Butter Lamb',
                'slug' => 'butter-lamb',
                'code' => '502',
                'bag_points' => '2',
                'description_en' => 'Tangy tomato curry with an Oriental nut mix. With tender chunks of prime New Zealand lamb',
                'description_dk' => 'Syrlig tomatcurry med orientalsk nøddemix. Med møre stykker af det bedste lammekød fra New Zealand',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 120,
            ],
            [
                'name' => 'Butter Lamb Kebab',
                'slug' => 'butter-lamb-kebab',
                'code' => '503',
                'bag_points' => '2',
                'description_en' => 'Tangy tomato curry with an Oriental nut mix with in house minced lamb kebabs (grilled).',
                'description_dk' => 'Syrlig tomatcurry med orientalsk nøddemix. Med hjemmelavede kebab af hakket og grillet lammekød',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Butter Paneer',
                'slug' => 'butter-paneer',
                'code' => '504',
                'bag_points' => '2',
                'description_en' => 'Tangy tomato curry with an Oriental nut mix. With un-aged, non-melting farmer cheese',
                'description_dk' => 'Syrlig tomatcurry med orientalsk nøddemix. Med traditionel indisk ulagret, fast ost',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => true,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Chicken Korma',
                'slug' => 'chicken-korma',
                'code' => '511',
                'bag_points' => '2',
                'description_en' => 'Slow-cooked curry with yoghurt & an Oriental nut mix. With tandoori chicken fillet marinated with spices',
                'description_dk' => 'Langtidstilberedt curry med yoghurt & orientalsk nøddemix. Med tandoori kyllingefilet marineret i krydderier',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Lamb Korma',
                'slug' => 'lamb-korma',
                'code' => '512',
                'bag_points' => '2',
                'description_en' => 'Slow-cooked curry with yoghurt & an Oriental nut mix. With tender chunks of prime New Zealand lamb',
                'description_dk' => 'Langtidstilberedt curry med yoghurt & orientalsk nøddemix. Med møre stykker af det bedste lammekød fra New Zealand',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 120,
            ],
            [
                'name' => 'Lamb Kebab Korma',
                'slug' => 'lamb-kebab-korma',
                'code' => '513',
                'bag_points' => '2',
                'description_en' => 'Slow-cooked curry with yoghurt & an Oriental nut mix with in house minced lamb kebabs (grilled).',
                'description_dk' => 'Langtidstilberedt curry med yoghurt & orientalsk nøddemix. Med hjemmelavede kebab af hakket og grillet lammekød',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Paneer Korma',
                'slug' => 'paneer-korma',
                'code' => '514',
                'bag_points' => '2',
                'description_en' => 'Slow-cooked curry with yoghurt & an Oriental nut mix. With un-aged, non-melting farmer cheese',
                'description_dk' => 'Langtidstilberedt curry med yoghurt & orientalsk nøddemix. Med traditionel indisk ulagret, fast ost',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => true,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Chicken Tikka Masala',
                'slug' => 'chicken-tikka-masala',
                'code' => '521',
                'bag_points' => '2',
                'description_en' => 'Curry with puréed nuts & ginger. With tandoori chicken fillet marinated with spices',
                'description_dk' => 'Curry med purerede nødder & ingefær. Med tandoori kyllingefilet marineret i krydderier',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Lamb Tikka Masala',
                'slug' => 'lamb-tikka-masala',
                'code' => '522',
                'bag_points' => '2',
                'description_en' => 'Curry with puréed nuts & ginger. With tender chunks of prime New Zealand lamb',
                'description_dk' => 'Curry med purerede nødder & ingefær. Med møre stykker af det bedste lammekød fra New Zealand',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 120,
            ],
            [
                'name' => 'Lamb Kebab Tikka Masala',
                'slug' => 'lamb-kebab-tikka-masala',
                'code' => '523',
                'bag_points' => '2',
                'description_en' => 'Curry with puréed nuts & ginger with in house minced lamb kebabs (grilled).',
                'description_dk' => 'Curry med purerede nødder & ingefær. Med hjemmelavede kebab af hakket og grillet lammekød',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Paneer Tikka Masala',
                'slug' => 'paneer-tikka-masala',
                'code' => '524',
                'bag_points' => '2',
                'description_en' => 'Curry with puréed nuts & ginger. With un-aged, non-melting farmer cheese',
                'description_dk' => 'Curry med purerede nødder & ingefær. Med traditionel indisk ulagret, fast ost',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => true,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Chicken Spinach',
                'slug' => 'chicken-spinach',
                'code' => '531',
                'bag_points' => '2',
                'description_en' => 'Whole-leafed spinach in a thick curry with a touch of fenugreek. With tandoori chicken fillet marinated with spices',
                'description_dk' => 'Hele spinatblade i en kraftig curry med et strejf af bukkehorn. Med tandoori kyllingefilet marineret i krydderier',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Lamb Spinach',
                'slug' => 'lamb-spinach',
                'code' => '532',
                'bag_points' => '2',
                'description_en' => 'Whole-leafed spinach in a thick curry with a touch of fenugreek. With tender chunks of prime New Zealand lamb',
                'description_dk' => 'Hele spinatblade i en kraftig curry med et strejf af bukkehorn. Med møre stykker af det bedste lammekød fra New Zealand',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 120,
            ],
            [
                'name' => 'Lamb Kebab Spinach',
                'slug' => 'lamb-kebab-spinach',
                'code' => '533',
                'bag_points' => '2',
                'description_en' => 'Whole-leafed spinach in a thick curry with a touch of fenugreek with in house minced lamb kebabs (grilled).',
                'description_dk' => 'Hele spinatblade i en kraftig curry med et strejf af bukkehorn. Med hjemmelavede kebab af hakket og grillet lammekød',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Paneer Spinach',
                'slug' => 'paneer-spinach',
                'code' => '534',
                'bag_points' => '2',
                'description_en' => 'Whole-leafed spinach in a thick curry with a touch of fenugreek. With un-aged, non-melting farmer cheese',
                'description_dk' => 'Hele spinatblade i en kraftig curry med et strejf af bukkehorn. Med traditionel indisk ulagret, fast ost',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => true,
                'vegan' => false,
                'nuts' => false,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Chicken Madras',
                'slug' => 'chicken-madras',
                'code' => '541',
                'bag_points' => '2',
                'description_en' => 'Classic spicy South Indian tomato-based curry. With tandoori chicken fillet marinated with spices',
                'description_dk' => 'Klassisk stærk sydindisk tomatbaseret curry. Med tandoori kyllingefilet marineret i krydderier',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => true,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Lamb Madras',
                'slug' => 'lamb-madras',
                'code' => '542',
                'bag_points' => '2',
                'description_en' => 'Classic spicy South Indian tomato-based curry. With tender chunks of prime New Zealand lamb',
                'description_dk' => 'Klassisk stærk sydindisk tomatbaseret curry. Med møre stykker af det bedste lammekød fra New Zealand',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => true,
                'order_chili' => true,
                'price' => 120,
            ],
            [
                'name' => 'Lamb Kebab Madras',
                'slug' => 'lamb-kebab-madras',
                'code' => '543',
                'bag_points' => '2',
                'description_en' => 'Classic spicy South Indian tomato-based curry with in house minced lamb kebabs (grilled).',
                'description_dk' => 'Klassisk stærk sydindisk tomatbaseret curry. Med hjemmelavede kebab af hakket og grillet lammekød',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => true,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Paneer Madras',
                'slug' => 'paneer-madras',
                'code' => '544',
                'bag_points' => '2',
                'description_en' => 'Classic spicy South Indian tomato-based curry. With un-aged, non-melting farmer cheese',
                'description_dk' => 'Klassisk stærk sydindisk tomatbaseret curry. Med traditionel indisk ulagret, fast ost',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => true,
                'vegan' => false,
                'nuts' => false,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => true,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Chicken Jeera Masala',
                'slug' => 'chicken-jeera-masala',
                'code' => '551',
                'bag_points' => '2',
                'description_en' => 'Spicy curry with cumin, ginger, garlic & fresh green chilli. With tandoori chicken fillet marinated with spices',
                'description_dk' => 'Krydret curry med spidskommen, ingefær, hvidløg & frisk grøn chili. Med tandoori kyllingefilet marineret i krydderier',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => true,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Lamb Jeera Masala',
                'slug' => 'lamb-jeera-masala',
                'code' => '552',
                'bag_points' => '2',
                'description_en' => 'Spicy curry with cumin, ginger, garlic & fresh green chilli. With tender chunks of prime New Zealand lamb',
                'description_dk' => 'Krydret curry med spidskommen, ingefær, hvidløg & frisk grøn chili. Med møre stykker af det bedste lammekød fra New Zealand',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => true,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 120,
            ],
            [
                'name' => 'Lamb Kebab Jeera Masala',
                'slug' => 'lamb-kebab-jeera-masala',
                'code' => '553',
                'bag_points' => '2',
                'description_en' => 'Spicy curry with cumin, ginger, garlic & fresh green chilli with in house minced lamb kebabs (grilled).',
                'description_dk' => 'Krydret curry med spidskommen, ingefær, hvidløg & frisk grøn chili. Med hjemmelavede kebab af hakket og grillet lammekød',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => true,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Paneer Jeera Masala',
                'slug' => 'paneer-jeera-masala',
                'code' => '554',
                'bag_points' => '2',
                'description_en' => 'Spicy curry with cumin, ginger, garlic & fresh green chilli. With un-aged, non-melting farmer cheese',
                'description_dk' => 'Krydret curry med spidskommen, ingefær, hvidløg & frisk grøn chili. Med traditionel indisk ulagret, fast ost',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => true,
                'vegan' => false,
                'nuts' => false,
                'dairy' => true,
                'gluten' => false,
                'chili' => true,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Coconut Tamarind Chicken',
                'slug' => 'coconut-tamarind-chicken',
                'code' => '561',
                'bag_points' => '2',
                'description_en' => 'A spicy fusion of North & South Indian curry with crushed red chilli. With tandoori chicken fillet marinated with spices',
                'description_dk' => 'En krydret fusion mellem nord- og sydindisk curry med knust rød chili. Med tandoori kyllingefilet marineret i krydderier',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => false,
                'gluten' => false,
                'chili' => true,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Coconut Tamarind Lamb',
                'slug' => 'coconut-tamarind-lamb',
                'code' => '562',
                'bag_points' => '2',
                'description_en' => 'A spicy fusion of North & South Indian curry with crushed red chilli. With tender chunks of prime New Zealand lamb',
                'description_dk' => 'En krydret fusion mellem nord- og sydindisk curry med knust rød chili. Med møre stykker af det bedste lammekød fra New Zealand',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => false,
                'gluten' => false,
                'chili' => true,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 120,
            ],
            [
                'name' => 'Coconut Tamarind Lamb Kebab',
                'slug' => 'coconut-tamarind-lamb-kebab',
                'code' => '563',
                'bag_points' => '2',
                'description_en' => 'A spicy fusion of North & South Indian curry with crushed red chilli with in house minced lamb kebabs (grilled).',
                'description_dk' => 'En krydret fusion mellem nord- og sydindisk curry med knust rød chili. Med hjemmelavede kebab af hakket og grillet lammekød',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => false,
                'vegan' => false,
                'nuts' => true,
                'dairy' => false,
                'gluten' => false,
                'chili' => true,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Coconut Tamarind Paneer',
                'slug' => 'coconut-tamarind-paneer',
                'code' => '564',
                'bag_points' => '2',
                'description_en' => 'A spicy fusion of North & South Indian curry with crushed red chilli. With un-aged, non-melting farmer cheese',
                'description_dk' => 'En krydret fusion mellem nord- og sydindisk curry med knust rød chili. Med traditionel indisk ulagret, fast ost',
                'portion' => 'approx. 400 g',
                'section' => 'bn-curries',
                'veg' => true,
                'vegan' => false,
                'nuts' => true,
                'dairy' => true,
                'gluten' => false,
                'chili' => true,
                'double_chili' => false,
                'order_chili' => true,
                'price' => 105,
            ],
            [
                'name' => 'Pilaoo Rice',
                'slug' => 'pilaoo-rice',
                'code' => '600',
                'bag_points' => '1',
                'description_en' => 'Steam-fried basmati rice',
                'description_dk' => 'Dampstegte basmati ris',
                'portion' => 'approx. 225 g',
                'section' => 'bn-sides',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 25,
            ],
            [
                'name' => 'Nan',
                'slug' => 'nan',
                'code' => '610',
                'bag_points' => '1',
                'description_en' => 'Traditional Indian leavened flatbread',
                'description_dk' => 'Traditionelt indisk gæret fladbrød',
                'portion' => '2 pieces',
                'section' => 'bn-sides',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => true,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 30,
            ],
            [
                'name' => 'Paratha',
                'slug' => 'paratha',
                'code' => '620',
                'bag_points' => '1',
                'description_en' => 'Unleavened wholemeal flatbread',
                'description_dk' => 'Ugæret fladbrød af fuldkornsmel',
                'portion' => '1 piece',
                'section' => 'bn-sides',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => true,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 30,
            ],
            [
                'name' => 'Raita',
                'slug' => 'raita',
                'code' => '630',
                'bag_points' => '1',
                'description_en' => 'Yoghurt dressing with shredded greens, potato & fresh herbs',
                'description_dk' => 'Yoghurtdressing med finthakkede grøntsager, kartoffel & friske urter',
                'portion' => 'approx. 150 g',
                'section' => 'bn-sides',
                'veg' => true,
                'vegan' => false,
                'nuts' => false,
                'dairy' => true,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 25,
            ],
            [
                'name' => 'Mango Chutney',
                'slug' => 'mango-chutney',
                'code' => '640',
                'bag_points' => '1',
                'description_en' => 'Homemade sweet mango chutney',
                'description_dk' => 'Hjemmelavet sød mangochutney',
                'portion' => 'approx. 150 g',
                'section' => 'bn-sides',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 25,
            ],
            [
                'name' => 'Papadums',
                'slug' => 'papadums',
                'code' => '650',
                'bag_points' => '1',
                'description_en' => 'Baked lentil crisps',
                'description_dk' => 'Bagte linsechips',
                'portion' => '4 pieces',
                'section' => 'bn-sides',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => true,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 30,
            ],
            [
                'name' => 'Chutneys',
                'slug' => 'chutneys',
                'code' => '660',
                'bag_points' => '1',
                'description_en' => '4 chutneys: mango / mint / tamarind / mixed pickles (may contain pits)',
                'description_dk' => '4 chutneys: mango / mynte / tamarind / indiske pickles (kan indeholde hårde kerner & sten)',
                'portion' => 'set of 4',
                'section' => 'bn-sides',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => true,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 30,
            ],
            [
                'name' => 'Chopped Salad',
                'slug' => 'chopped-salad',
                'code' => '670',
                'bag_points' => '1',
                'description_en' => 'Exotic salad with spicy dressing',
                'description_dk' => 'Eksotisk salat med pikant dressing',
                'portion' => 'approx. 150 g',
                'section' => 'bn-sides',
                'veg' => false,
                'vegan' => true,
                'nuts' => false,
                'dairy' => false,
                'gluten' => false,
                'chili' => false,
                'double_chili' => false,
                'order_chili' => false,
                'price' => 40,
            ],
        ]);
    }
}
