<?php

return [

    "Was it easy / user friendly  ordering at Bindia?" => "User Friendly UI/UX",
    "Was ordering at Bindia.dk easy and user-friendly?" => "User Friendly UI/UX",
    "Was it easy (user friendly) ordering at bindia.dk?" => "User Friendly UI/UX",
    "Was it user friendly ordering at bindia.dk?" => "User Friendly UI/UX",
    "Were you attended with care by the staff?" => "Service",
    "Were you attended with care by our staff at the shop?" => "Service",
    "Was your food ready at the agreed time?" => "Food Ready @",
    "Did you like the food?" => "Food",
    "How did you like the food?" => "Food",
    "Which Bindia location is your feedback about?" => "Location",
    "Were you satisfied with the general hygiene at Bindia?" => "Hygiene",
    "Were you satisfied with the general hygienic standard in Bindia?" => "Hygiene",
    "Are you satisfied with the overall Bindia experience?" => "Overall",
    "Were you satisfied with the overall hygiene in Bindia?" => "Overall",
    "Tell us what can be done better?" => "Comment",
    "Tell us what can be done better" => "Comment",
    "Please tell us what we’re doing well." => "Comment",
    "Any compliments to Bindia?" => "Comment",
    "Please let us know how we can improve." => "Suggestion",
    "Was it easy (user friendly) ordering at Bindia?" => "User Friendly UI/UX",
    "Was the courier friendly & service minded?" => "Service",
    "Was the courier friendly and service-minded?" => "Service",
    "Was the food delivered on time?" => "Food Ready @",
    "Was order ready on time?" => "Food Ready @",
    "Was the communication with Bindia satisfactory?" => "Communication",
    "Was the food packed properly?" => "Packing",
    "Were you attended with care by our staff?" => "Service",
    "Was food enough?" => "Quantity",
    "Was the food delivered at agreed time?" => "Food Ready @",
    "Was your food ready on the agreed time?" => "Food Ready @",
    "Was the driver friendly & service minded?" => "Service",
    "May we use your feedback at Bindia.dk? (without full name and contact details)" => "Use Feedback",
    "May we use your feedback at Bindia.dk? (without full name & contact details)" => "Use Feedback",
    "Can we use your feedback on our website please?" => "Use Feedback",
    "If you just forgot something in the bag (raita, papadums etc.), just write it here, and go directly to question 6" => "Forgot",
    "Describe the problem as the customer states it?" => "Problem",
    "Your opinion about the problem" => "Opinion",
    "Your action" => "Action",
    "Your suggestion to prevent a similar error" => "Suggestion",
    "Any suggestions for improvement?" => "Suggestion",
    "Your recommended action (Gift card / Apology / etc.)" => "Recommendation",
    "Who's fault is this?" => "Fault",
];
